### ISSUE TITLE
无法扫描依赖的package (git)

### ISSUE THREAD

**Issue by hilondev** [fluttercandies/ff_annotation_route#37]
```
name: demo_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  package_a:
    git: git@github.com:hilondev/package_a.git

  package_base:
    git: git@github.com:hilondev/package_base.git

  ff_annotation_route_library: ^3.0.0
  ff_annotation_route: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


```

---- 执行 ff_route命令后：
```
ff_route  --super-arguments --null-safety --no-arguments-case-sensitive -s  --git package_a

```
Scanning package : demo_project
Found annotation route : lib/main.dart ------ class : MyHomePage
Generate : lib/demo_project_routes.dart
Generate : lib/demo_project_route.dart

并没有package_a的路由生成，demo_project_routes.dart文件里没有package_a相关的路由信息
